// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

//go:build test

package hasher

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockHasher creates a new instance of MockHasher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHasher(t interface {
	mock.TestingT
	Cleanup(func())
},
) *MockHasher {
	mock := &MockHasher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHasher is an autogenerated mock type for the Hasher type
type MockHasher struct {
	mock.Mock
}

type MockHasher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHasher) EXPECT() *MockHasher_Expecter {
	return &MockHasher_Expecter{mock: &_m.Mock}
}

// Compare provides a mock function for the type MockHasher
func (_mock *MockHasher) Compare(ctx context.Context, hashedPassword []byte, password []byte) error {
	ret := _mock.Called(ctx, hashedPassword, password)

	if len(ret) == 0 {
		panic("no return value specified for Compare")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte, []byte) error); ok {
		r0 = returnFunc(ctx, hashedPassword, password)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHasher_Compare_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Compare'
type MockHasher_Compare_Call struct {
	*mock.Call
}

// Compare is a helper method to define mock.On call
//   - ctx context.Context
//   - hashedPassword []byte
//   - password []byte
func (_e *MockHasher_Expecter) Compare(ctx interface{}, hashedPassword interface{}, password interface{}) *MockHasher_Compare_Call {
	return &MockHasher_Compare_Call{Call: _e.mock.On("Compare", ctx, hashedPassword, password)}
}

func (_c *MockHasher_Compare_Call) Run(run func(ctx context.Context, hashedPassword []byte, password []byte)) *MockHasher_Compare_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockHasher_Compare_Call) Return(err error) *MockHasher_Compare_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHasher_Compare_Call) RunAndReturn(run func(ctx context.Context, hashedPassword []byte, password []byte) error) *MockHasher_Compare_Call {
	_c.Call.Return(run)
	return _c
}

// Hash provides a mock function for the type MockHasher
func (_mock *MockHasher) Hash(ctx context.Context, password []byte) ([]byte, error) {
	ret := _mock.Called(ctx, password)

	if len(ret) == 0 {
		panic("no return value specified for Hash")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte) ([]byte, error)); ok {
		return returnFunc(ctx, password)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte) []byte); ok {
		r0 = returnFunc(ctx, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []byte) error); ok {
		r1 = returnFunc(ctx, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHasher_Hash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Hash'
type MockHasher_Hash_Call struct {
	*mock.Call
}

// Hash is a helper method to define mock.On call
//   - ctx context.Context
//   - password []byte
func (_e *MockHasher_Expecter) Hash(ctx interface{}, password interface{}) *MockHasher_Hash_Call {
	return &MockHasher_Hash_Call{Call: _e.mock.On("Hash", ctx, password)}
}

func (_c *MockHasher_Hash_Call) Run(run func(ctx context.Context, password []byte)) *MockHasher_Hash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHasher_Hash_Call) Return(bytes []byte, err error) *MockHasher_Hash_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockHasher_Hash_Call) RunAndReturn(run func(ctx context.Context, password []byte) ([]byte, error)) *MockHasher_Hash_Call {
	_c.Call.Return(run)
	return _c
}
